### ISSUE TITLE
Get-CertificateTemplate New-Object Constructor Exception

### ISSUE THREAD

**Issue by kevanbrown** [PKISolutions/PSPKI#79]
Don't know exactly what in the certificate templates is causing this, but only a subset of the certificate templates in AD are returned from Get-CertificateTemplate.  The rest throw this New-Object constructor exception:

New-Object : Exception calling ".ctor" with "1" argument(s): "Exception has been thrown by the target of an
invocation."
At C:\Users\User\Documents\WindowsPowerShell\Modules\PSPKI\Server\Get-CertificateTemplate.ps1:67 char:48
+ ... ach-Object {New-Object PKI.CertificateTemplates.CertificateTemplate $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by Crypt32** [comment]
Can you provide stack trace? When exception is thrown, run the command:

```
$error[0].Exception.InnerException.StackTrace
```
and post the output here.

**Comment by kevanbrown** [comment]
PS C:\> $error[0].Exception.InnerException.StackTrace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, Cultu
reInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at System.Security.Cryptography.Oid2.computeOidHash(String oid)
   at System.Security.Cryptography.Oid2.initializeDS(String oid, OidGroupEnum group)
   at PKI.CertificateTemplates.CertificateTemplateSettings.get_extensions()
   at PKI.CertificateTemplates.CertificateTemplate.m_fillproperties(String ldapPath)

**Comment by Crypt32** [comment]
I made several tests and can't repro this error. But the error suggests that the code cannot create an instance of MD5 class. Can you run this command on a computer where code fails:

```
[System.Security.Cryptography.MD5]::Create()
```
does it work, or throw exception?

**Comment by Crypt32** [comment]
Thread isn't updated for a long time.
